### ISSUE TITLE
Animated favicon concurrency: callback called twice

### ISSUE THREAD

**Issue by emilv** [nicolasbize/faviconx#1]
I triggered this problem while playing around on the demo page. To reproduce:
1. Start "Status Icons" demo
2. Before it finishes, start "Callbacks demo"
3. Wait for animation to finish
4. Result: You get two `Bonjour!` alerts, so that callback got called twice!

**Comment by nicolasbize** [comment]
Ah yes indeed. I'll fix this. thanks

**Comment by nicolasbize** [comment]
Fixed in 1.0.1. Thanks for the report.
