### ISSUE TITLE
Resetting a currently animating icon

### ISSUE THREAD

**Issue by emilv** [nicolasbize/faviconx#3]
If I `.reset` a currently animating the animation starts going backwards and the original favicon is not restored. To reproduce this on the demo page:
1. Start the "Status Icons" demo
2. Before it finishes, start the "Reset" demo

**Comment by nicolasbize** [comment]
Thanks I'll fix this

**Comment by nicolasbize** [comment]
Fixed in 1.0.1. Thanks for the report.
